### ISSUE TITLE
Password constraints upon sign up 

### ISSUE THREAD

**Issue by chenpionaar1998** [mariamarab/street-smart#34]
The current password contraints are in red on the signup page. The constraints should be addressed more dynamic rather than direct text on the screen.

**Comment by swa181** [comment]
![image](https://user-images.githubusercontent.com/38788856/60739899-6f7ceb80-9f18-11e9-94ad-8355d00b7d7a.png)

More detail: I think we could implement the password constraints such that they only show/complain when the user has entered an invalid character or does not meet our password standards. The wall of red looks like a little scary for any new user thats trying to sign up.

**Comment by swa181** [comment]
Linking PR #36
